### ISSUE TITLE
Logo changes are annoying

### ISSUE THREAD

**Issue by StarrKiss** [hammerhead-n5/altlinuxlogo#4]
The old logo with the flipper , this one-

![image](https://user-images.githubusercontent.com/13007697/89475648-2f58ef80-d74e-11ea-9a02-059993b626a6.png)

looked classy and sleek. The new logos with the white borders around annoying bold fonts is ugly as hell! Please re-upload this svg, I had to go digging through the commits in order to find it when I wanted to print out a sticker cause the new one is shit.

**Comment by Vuaqava** [comment]
https://github.com/hammerhead-n5/altlinuxlogo/tree/fe8aa05a5bd5b029c5e63ffdbd7e512c017cd42a/SVG

**Comment by Vuaqava** [comment]
Sorry, this is the new account of hammerhead-n5
